#!/bin/bash
#adduser qiqi
dscl . -create /User/Julie
#groupadd team1
dscl . -create /Groups/Not_Trustworthy
#usermod -a -G team1 qiqi
dscl . append /Groups/Not_Trustworthy GroupMembership $Julie
cp /Users/ciarra/history.txt .
chmod 754 history.txt
touch empty.txt
touch also_empty.txt
rm empty.txt
